[dev]
  publish = "dist"
  command = "npm run dev"
  framework = "#static"

[build]
  publish = "dist"
  command = "npm run build"
  framework = "#static"

[functions]
  directory = "functions/"

[[redirects]]
  from = "api/v1/*"
  to= ".netlify/functions/:splat"
  status = 200