[dev]
  publish = "dist"
  command = "npm run dev"
  functions = "functions"

[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/api/v1/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200